### PR TITLE
Add missing type hints

### PR DESCRIPTION
**Pull request by heckad**

### CODE REVIEW

**Comment by aucampia** [comment]
Happy to see some type hints, but I don't see any type checker as part of the CI pipeline, should this not be in place first?

**Comment by aucampia** [comment]
Let me raise a separate issue for that actually.

**Comment by heckad** [comment]
I added only those types that help pass typechaking in my project. I am sure that after a new version with a `py.typed` file is released, the community will quickly add the missing types. And only then it will be possible to think about checking the project itself and arranging internal types. Everything big starts from small.

**Comment by ptmcg** [comment]
Sorry for the delay - was on a business trip, so was focused on the day job.

I also appreciate your comments on when/how pyparsing might _someday_ get type checking into the CI, but it won't be for a while yet. (Since I still support Py3.6, I can't even add `from __future__ import annotations`)

**Comment by heckad** [comment]
@ptmcg, do you have any plans for a new release?

**Pull request merged**
