### PR TITLE
Remove unused Scrutinizer CI configuration

### PR DESCRIPTION
**Pull request by jdufresne**
Scrutinizer CI is not enabled for this repository. The files are
outdated and unused.

### CODE REVIEW

**Comment by ptmcg** [comment]
I've asked @cngkaygusuz  via the team discussions on how to activate this, since it was their original proposal, and I think about 90% implemented, short of some activation step on my part which I am still unclear on.

**Comment by jdufresne** [comment]
Does this tool offer anything that isn't already being handled by Travis or couldn't be handled by flake8?

**Comment by cngkaygusuz** [comment]
I shall reply to this issue today.

**Comment by ptmcg** [comment]
The project updates have now included calls to codecov and tox, so I don't see any advantage to using Scrutinizer.

**Pull request merged**
