### PR TITLE
Drop support for EOL Python 2.6 and 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Python 2.6 and 3.3 are EOL and no longer receiving security updates (or any updates) from the core Python team.

They're also little used.

Here's the pip installs for pyparsing from PyPI for July 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  47.93% |      1,114,577 |
| 3.6            |  41.48% |        964,630 |
| 3.5            |   5.84% |        135,685 |
| 3.4            |   2.92% |         67,946 |
| 3.7            |   1.70% |         39,504 |
| 2.6            |   0.07% |          1,671 |
| 3.3            |   0.05% |          1,047 |
| 3.8            |   0.01% |            208 |
| 3.2            |   0.00% |             86 |
| None           |   0.00% |              4 |
| Total          |         |      2,325,358 |

Source: `pypinfo --start-date 2018-07-01 --end-date 2018-07-31 --percent --markdown pyparsing pyversion`

# Changes

This PR:
* drops support for EOL Python 2.6 and 3.3 and removes some redundant code
* adds `python_requires` to setup.py to help pip
* adds Python 3.7 to the Trove classifiers
* upgrades Python syntax using https://github.com/asottile/pyupgrade

# Tests

Tests pass on macOS High Sierra with Python 2.7 and 3.7:

```
⌂73% [hugo:/private/tmp/pyparsing] rm-eol ± p2 unitTests.py
Beginning test of pyparsing, version 2.2.0
Python version 2.7.15 (default, Jun 17 2018, 12:46:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
...............................................................................................................................................................
----------------------------------------------------------------------
Ran 159 tests in 2.815s

OK
⌂73% [hugo:/private/tmp/pyparsing] rm-eol 3s ± p3 unitTests.py
Beginning test of pyparsing, version 2.2.0
Python version 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)]
...............................................................................................................................................................
----------------------------------------------------------------------
Ran 159 tests in 3.284s

OK
```

### CODE REVIEW

**Comment by ptmcg** [comment]
Glad for the help, but I would like to retain support for 2.6 at this time. Your PRs are a huge help, btw.

**Comment by hugovk** [comment]
You're welcome, and no problem!

Would you also like to keep 3.3 support a while longer?

**Comment by ptmcg** [comment]
Yes to 3.3 also, but that should be sufficient for 3.x. The 3.x versions have been so long in adoption that their legacy installations are small compared to 2.x pre 2.7, and I finally cut the cord on 2.5. I had a specific request about 3.4.0, so I would like to keep support for that version for a bit yet.

**Comment by ptmcg** [comment]
The pyupgrade changes are probably okay for the examples, but not for the pyparsing code itself, nor for the unit tests.

**Comment by hugovk** [comment]
I'll make a PR to upgrade the examples.

**Pull request closed without merging**
