### PR TITLE
Revise ParserElement.parseString docstring

### PR DESCRIPTION
**Pull request by cngkaygusuz**

### CODE REVIEW

**Comment by paulmcg-iio** [comment]
Is the intent that all the example code in docstrings will be converted to doctest? How does this translate to sphinx-generated docs?

**Comment by cngkaygusuz** [comment]
Sphinx should be able to handle it. I'll test it tomorrow and reopen the PR.

**Comment by cngkaygusuz** [comment]
As expected, sphinx handles the doctests gracefully. The new style of function API definition also looks nicer in my opinion. I am attaching an image of the outcome.

image

**Comment by ptmcg** [comment]
Approved - carry on!

**Pull request merged**
