### PR TITLE
Minor code refactoring/denesting for results.py

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
This PR is a part of #519.

### CODE REVIEW

**Comment by ptmcg** [comment]
A number of unit tests fail with these changes. I'm grateful for your efforts, I'll see if I can help troubleshoot which specific changes are at issue.

**Comment by ptmcg** [comment]
The changes to values() and items() cause the tests to fail. It is important that `__getitem__` is called to get the values and items for the keys, rather than just returning the values and items directly from tokdict. I can add some more explanatory comments on why they have to be the way they are, to make this clearer.

Also, please do not replace `not not expr` with `bool (expr)`. It is a micro-optimization, but anything I can do to shave cycles at parsing time is a plus, to help pyparsing's parse-time performance.

I like all the early exit code that gets rid of a fair bit of nesting, thanks!

**Comment by jayaddison** [comment]
@InSyncWithFoo @ptmcg could you double-check the HTML file added in commit 865fccde7c956f95dc8544586a927cc8703de076?  It seems unrelated to the rest of the pull request, as far as I can tell.

**Comment by ptmcg** [comment]
I'll revert it to its former state - thanks for the catch.

**Comment by jayaddison** [comment]
Thanks both!

**Pull request merged**
