### PR TITLE
Example BigQuery view SQL parser

### PR DESCRIPTION
**Pull request by smedberg**
A parser to extract table names from the SQL for a BigQuery view.  Given the SQL of a view, it returns information about the tables that are being selected from.

### CODE REVIEW

**Comment by ptmcg** [comment]
Wow! Fantastic and comprehensive work. Thank you for following the coding styles I am trying to promote elsewhere. Just a couple of comments:
- you create a new parser every time you call _parse(), within the body of _parse(); please extract out to its own staticmethod or classmethod the returns a parser; in fact, it doesn't look like this parser keeps any state, so there should be no harm in reusing it across multiple calls to _parse(); having a method that just returns the parser makes testing easier
- I like your style for defining the keywords
- please replace people's names with fictitious names or fictional characters (I find cartoon characters to be obviously fictitious, yet suitable for valid testing)
- at least one place you have `quotedString('"')` where I think you want `QuotedString('"')`
- watch out for expressions like `Word(alphanums + '_')` for identifiers - they will match integers as if they were identifiers
- expressions like `Word(alphas + '$' + '%' + '!')` can also be written `Word(alphas + '$%!')` (but both are equivalent, purely a style bit)
- you may have some ungrouped expressions with a results name that also contain expressions with results names, and this may not give you the hierarchical naming I think you are trying to achieve; try setting `__diag__.warn_ungrouped_named_tokens_in_collection` to True and see if this helps identify these cases; resolution is to Group the outer expression (I'll also be very interested in how well this works for you, as these diagnostic switches are brand new in 2.4.2)
- please add a header with the name of the script, short description, and your name as author

By submitting this PR, you are releasing it under the same MIT license as the rest of pyparsing. You probably already know that, but I want to be sure it is clear.

Regards and thanks!
-- Paul

**Comment by smedberg** [comment]
Thanks for the quick and complete feedback- I'll try to address these issues today!

**Comment by smedberg** [comment]
Regarding
> please replace people's names with fictitious names or fictional characters (I find cartoon characters to be obviously fictitious, yet suitable for valid testing)
I got those SQL statements directly from the BigQuery documentation.  My intention was to prove that my parser could handle the documented sample SQL exactly as presented by Google.  For example, this SQL statement:
```
            WITH finishers AS
             (SELECT 'Sophia Liu' as name,
              TIMESTAMP '2016-10-18 2:51:45' as finish_time,
              'F30-34' as division
              UNION ALL SELECT 'Lisa Stelzner', TIMESTAMP '2016-10-18 2:54:11', 'F35-39'
              UNION ALL SELECT 'Nikki Leith', TIMESTAMP '2016-10-18 2:59:01', 'F30-34'
              UNION ALL SELECT 'Lauren Matthews', TIMESTAMP '2016-10-18 3:01:17', 'F35-39'
              UNION ALL SELECT 'Desiree Berry', TIMESTAMP '2016-10-18 3:05:42', 'F35-39'
              UNION ALL SELECT 'Suzy Slane', TIMESTAMP '2016-10-18 3:06:24', 'F35-39'
              UNION ALL SELECT 'Jen Edwards', TIMESTAMP '2016-10-18 3:06:36', 'F30-34'
              UNION ALL SELECT 'Meghan Lederer', TIMESTAMP '2016-10-18 3:07:41', 'F30-34'
              UNION ALL SELECT 'Carly Forte', TIMESTAMP '2016-10-18 3:08:58', 'F25-29'
              UNION ALL SELECT 'Lauren Reasoner', TIMESTAMP '2016-10-18 3:10:14', 'F30-34')
            SELECT name,
              FORMAT_TIMESTAMP('%X', finish_time) AS finish_time,
              division,
              FORMAT_TIMESTAMP('%X', fastest_time) AS fastest_time,
              TIMESTAMP_DIFF(finish_time, fastest_time, SECOND) AS delta_in_seconds
            FROM (
              SELECT name,
              finish_time,
              division,
              FIRST_VALUE(finish_time)
                OVER (PARTITION BY division ORDER BY finish_time ASC
                ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS fastest_time
              FROM finishers)
```
comes from https://cloud.google.com/bigquery/docs/reference/standard-sql/navigation_functions (search for `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS fastest_time` to find it on the page.)
In principle, I'd prefer to keep those SQL statements exactly as they appear in the documentation- my goal is to prove that my parser matches the documentation.
However, if you feel strongly, I'm happy to replace the names with more obviously fictional ones- please let me know your preference.

**Comment by ptmcg** [comment]
Good enough for Google is good enough for me. Please cite the source if you haven't already.

**Comment by smedberg** [comment]
@ptmcg I tried to address all of your comments- `__diag__.warn_ungrouped_named_tokens_in_collection` seemed to work well

**Comment by ptmcg** [comment]
After I merge this, I might do a little more work on your classes, do you mind? Mostly in locating state within an instance instead of in the class itself, so that multiple parser instances could run without stepping on each other.

**Comment by smedberg** [comment]
That would be great, thanks!

**Pull request merged**
