### PR TITLE
Diagram improvements IV

### PR DESCRIPTION
**Pull request by TMiguelT**
## Changes:

* Skip a lot more "empty" groups in the diagram that don't add much to the output
* Fix for elements with `name=None`, with a new test
* Add some assertions to the existing tests to fix major breaking changes
* Sort all elements by order found, which should help readability
* Use new `element.recurse()` method for listing children
* Use the new naming API discussed in #223 to great effect

## Example
The new diagram for the SQL grammar: 
[SQLRailroadv3.pdf](https://github.com/pyparsing/pyparsing/files/4827084/SQLRailroadv3.pdf)

## Blocked by
* [x] Resolution of https://github.com/pyparsing/pyparsing/issues/223#issuecomment-647950809. It's currently unclear how I can access *only user-defined* names, but not auto-generated names, and vice-versa. This is required for some final changes.

## Todos
* [x] Update the documentation with the newest SQL example diagram before we merge
* [x] Uncomment [this stuff](https://github.com/pyparsing/pyparsing/pull/225/files#diff-6eaf53d6899abb5f5d821bf06bc048e1R377-R387) once the above is resolved.

### CODE REVIEW

**Comment by ptmcg** [comment]
`name` attribute will contain user-defined names; `strRepr` will contain the internally-generated names; `str()` will return `name` if not None, else `strRepr`. Thanks for the fix on `NotImplemented` vs `NotImplementedError`.

**Comment by TMiguelT** [comment]
`name` will contain user-defined names, or it is supposed to now? Because currently it doesn't:

* https://github.com/pyparsing/pyparsing/blob/master/pyparsing/core.py#L1739
* https://github.com/pyparsing/pyparsing/blob/master/pyparsing/core.py#L1788
* https://github.com/pyparsing/pyparsing/blob/master/pyparsing/core.py#L1799
* https://github.com/pyparsing/pyparsing/blob/master/pyparsing/core.py#L1836

etc

**Comment by ptmcg** [comment]
Hmmm, this is a bigger issue than I gave it credit. I am composing an email with more details so we don't clutter this PR with back-and-forth comments, and then we can summarize the plan in this PR once we settle on one.

**Comment by TMiguelT** [comment]
Feel free to put all your thoughts into #223, since that's really what the issue is for.

**Comment by TMiguelT** [comment]
Okay this is now ready, thanks for the naming API fixes in #223!

Although I'm happy for this to be merged as-is, I honestly wouldn't mind a quick eye over the actual code at some point. It needn't be now, but before this is released into a production version.

For example, I have some "simplifying" code that basically prunes the token tree in order to avoid processing certain elements that clog up the diagram. I entirely skip past[`Group` and `Forward` that themselves don't have a custom name](https://github.com/TMiguelT/pyparsing/blob/diagram-improvements/pyparsing/diagram/__init__.py#L300) and I extract [`Empty` elements that don't have a `customName`](https://github.com/TMiguelT/pyparsing/blob/diagram-improvements/pyparsing/diagram/__init__.py#L355-L357). Are there any other elements that fit into these two categories that I should be including? Or is there perhaps an edge case I'm forgetting by doing this?

**Comment by TMiguelT** [comment]
Oh and perhaps another point for discussion: I'm abusing the "group" element in the railroad library a fair bit (which adds these dotted lines around things) 
image.

However I use these to label `customNames` as well as `ParseElementEnhance` as well as some `Groups`, so I'm open to suggestions to a more consistent way to label all these things.

**Comment by ptmcg** [comment]
I'm going to merge as-is, we are still in alpha pre-releases so there is room for refinements. I'll need to give this some runthroughs with some parsers to get a feel for these questions.

**Comment by ptmcg** [comment]
I think another type you might want to suppress would be `FollowedBy`, or at least the internal `_FB` subclass used in `infixNotation`.

I'm also happy to see the new Word default strings in these diagrams.

**Comment by TMiguelT** [comment]
> I think another type you might want to suppress would be FollowedBy, or at least the internal _FB subclass used in infixNotation

Agreed, I'll try to add this in a future update

> I'm also happy to see the new Word default strings in these diagrams.

Indeed! Part of the naming changes I requested in #223 were to allow me to still show the accepted characters of terminals even if they have a custom name

**Pull request merged**
